### PR TITLE
Support android gradle plugin 1.1.0 up

### PR DESCRIPTION
**Pull request by polenchheang**
Fix issue https://github.com/uPhyca/gradle-android-aspectj-plugin/issues/14

Change-Id: I44c901402756f4d9388f6d5149e0e23b9eebce77

### CODE REVIEW

**Comment by carlonzo** [comment]
merge it please!

**Comment by esmasui** [comment]
Thanks for your contributions!

**Comment by polenchheang** [comment]
Glad that you merged that.

**Comment by esmasui** [comment]
I've released the version 0.9.10 to maven central, please check it out about 2 hours later.

**Pull request merged**
